In [2]:
# intro to numpy arrays
# - allows us to do mathematical operations, scientific computation & analysis in python language
# -Numerical Python
# -Arrays= ndarrays
# -multidimensional,homogenous,can do element-wise ,easy to access

In [1]:
# dimensions in array

# 0D array-scalar: an array made up of only one numerical value
# 1D array-vector:list of elements
# 2D: list of elements are the elements
# 3D: 2D arrays are the elements

In [3]:
# arrays from lists or tuples
# np.array()

import numpy as np

my_list = [1,2,3,4,5]

arr1 = np.array(my_list)
arr1

array([1, 2, 3, 4, 5])

In [5]:
my_list = [[1,2,3],[4,5,6]]
arr2 = np.array(my_list)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# array from random
arr3 = np.random.rand(2,3)
arr3

array([[0.64668171, 0.82050997, 0.88082228],
       [0.05269202, 0.87048306, 0.82441602]])

In [ ]:
arr4 = np.random.randint(5,size=(5,5))
print(arr4)

[[1 0 3 4 2]
 [0 2 1 4 1]
 [2 4 2 0 1]
 [2 0 2 1 3]
 [0 3 2 1 4]]


In [8]:
arr5 = np.full((2,3,4),9)
arr5

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [9]:
arr6 = np.arange(0,50,2)
arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [10]:
arr7 = np.identity(4)
arr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
arr8 = np.eye(4,k=1)
arr8

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [18]:
arr9 = np.random.randint(35,40,size=(5,7))
print(arr9)

[[38 36 39 39 36 36 36]
 [39 38 35 35 38 38 35]
 [37 36 35 35 36 37 37]
 [37 38 35 36 36 35 35]
 [36 39 36 37 38 36 38]]


In [20]:
arr10 = np.random.randint(25,size=(30,30))
arr10

array([[11, 23, 23,  7, 21,  8, 21,  0, 14,  1, 19,  3,  9,  5,  7, 12,
         8,  2, 23,  4, 14, 23,  4,  9,  4,  7, 23, 14,  6, 20],
       [ 1,  8, 16, 12, 22,  1,  7, 19, 17, 19, 10,  8, 13, 23,  6, 13,
         7,  1, 15,  2, 16, 17,  4,  4, 11,  2, 15, 19, 22, 19],
       [19, 19,  0, 20, 19,  6,  3,  2, 21,  9, 11, 13, 16,  0, 13, 16,
         2, 19, 17, 24, 21,  2, 13,  3,  1,  2, 17,  1,  6, 12],
       [19, 16, 11, 22, 17,  5,  1, 24, 13, 23, 22, 17,  0,  9, 22, 24,
         6,  7,  7,  4, 16,  7,  8, 11, 10, 16, 15, 14, 19, 21],
       [13, 19, 24,  2, 18, 20, 14, 24, 23,  3,  4, 23, 18,  0,  4, 21,
         9,  8,  4,  6, 19,  0,  7, 18, 15, 21,  0, 16,  7, 24],
       [ 9, 18, 20,  2,  9, 19,  5,  7, 22,  5,  9,  9,  8,  4, 17,  6,
         0,  5,  2, 13, 13, 24, 15, 15, 15, 18, 22, 21, 18, 16],
       [21,  2, 18, 15, 17, 22,  8,  2, 15, 10, 17, 21,  4, 18,  6,  2,
         2, 16, 16, 15, 23,  7,  6,  3,  4,  4,  1, 18, 22, 16],
       [22, 14,  2,  2, 22,  3, 23,  5,  

In [32]:
# array attributes-characteristics
# -dimensions
# -size
# -shape
# -data type

import numpy as np

x1 = np.random.randint(50,size=(3,5)).reshape(5,3)
print(x1)

[[ 2 30 17]
 [37 31 25]
 [21 40 14]
 [40 35 40]
 [23 23 17]]


In [33]:
x1.reshape(3,5)

array([[ 2, 30, 17, 37, 31],
       [25, 21, 40, 14, 40],
       [35, 40, 23, 23, 17]], dtype=int32)

In [25]:
print(x1.shape)

(3, 5)


In [26]:
print(x1.ndim)

2


In [27]:
print(x1.dtype)

int32


In [29]:
print(x1.size)

15


# indexing
accessing element in array

In [36]:
x2 = np.arange(10,20,2)
print(x2[3])

16


In [40]:
x3 = np.arange(10,100,3).reshape(2,5,3)
x3

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34],
        [37, 40, 43],
        [46, 49, 52]],

       [[55, 58, 61],
        [64, 67, 70],
        [73, 76, 79],
        [82, 85, 88],
        [91, 94, 97]]])

In [43]:
x3[1,2,1]

np.int64(100)

In [45]:
x3[1,2,1]=100
x3

array([[[ 10,  13,  16],
        [ 19,  22,  25],
        [ 28,  31,  34],
        [ 37,  40,  43],
        [ 46,  49,  52]],

       [[ 55,  58,  61],
        [ 64,  67,  70],
        [ 73, 100,  79],
        [ 82,  85,  88],
        [ 91,  94,  97]]])

# slicing

In [47]:
# (start,stop,step)

x4 = np.arange(10)
x4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x4[4:7]

array([4, 5, 6])

In [106]:
x5 = np.array([23,56,78,90,67,50,45,89,34,69,33,54]).reshape(3,4)
x5

array([[23, 56, 78, 90],
       [67, 50, 45, 89],
       [34, 69, 33, 54]])

In [66]:
# [row,colomun]

x5[1:3,1]

array([67, 89])

In [67]:
x5[0:3,2]

array([78, 50, 34])

In [72]:
x5[0:2,1:3]

array([[56, 78],
       [67, 50]])

In [84]:
x6 = np.array([23,56,78,90,67,50,45,89,34,10,30,29]).reshape(3,4)
x6

array([[23, 56, 78, 90],
       [67, 50, 45, 89],
       [34, 10, 30, 29]])

In [78]:
x6[:,3]

array([90, 89, 29])

In [86]:
x4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# rearrange from the back
x4[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# PALINDROME
a = 'BOB'
b = a[::-1]
if a == b :
    print('This is a palindrome')
else:
    print('This is not a palindrome')

This is not a palindrome


# Vectorization
Universal functions-arithmetic,trigonometic,aggregation

In [95]:
x5

array([[23, 56, 78],
       [90, 67, 50],
       [45, 89, 34]])

In [96]:
np.add(x5,5)

array([[28, 61, 83],
       [95, 72, 55],
       [50, 94, 39]])

In [97]:
np.power(x5,2)

array([[ 529, 3136, 6084],
       [8100, 4489, 2500],
       [2025, 7921, 1156]])

In [98]:
np.sqrt(x5)

array([[4.79583152, 7.48331477, 8.83176087],
       [9.48683298, 8.18535277, 7.07106781],
       [6.70820393, 9.43398113, 5.83095189]])

In [101]:
x7 = np.random.rand(20)
x7

array([0.0980353 , 0.82227406, 0.28844951, 0.26919327, 0.96172306,
       0.34126439, 0.36572323, 0.27725751, 0.74028978, 0.41987498,
       0.34410471, 0.11522783, 0.01707069, 0.90531674, 0.36103965,
       0.94890951, 0.58568859, 0.17404319, 0.35317346, 0.2074541 ])

In [104]:
np.tan(x7)

array([0.09835059, 1.07661166, 0.296725  , 0.2758898 , 1.43360888,
       0.35516012, 0.38295112, 0.2845874 , 0.91362106, 0.4464226 ,
       0.35836195, 0.11574053, 0.01707235, 1.27401087, 0.37759026,
       1.39516457, 0.66332934, 0.17582206, 0.36862899, 0.21048233])

In [113]:
x5

array([[23, 56, 78, 90],
       [67, 50, 45, 89],
       [34, 69, 33, 54]])

In [115]:
np.sum(x5, axis=1)

array([247, 251, 190])

In [116]:
np.sum(x5, axis=0)

array([124, 175, 156, 233])

In [118]:
arr1=np.arange(5)
arr2=np.array([1,2,3,4,5])
np.add(arr1,arr2)

array([1, 3, 5, 7, 9])

In [119]:
arr1

array([0, 1, 2, 3, 4])

# BROADCASTING
if trailing dimension is 1 or equal
same or 1
broadcast the array that has the smaller dimension into the bigger

In [ ]:
arr1 = np.array([10,20,30])
arr2 = np.random.randint(7,size=(3,2))
# print(arr1)
# print(arr2)
np.add(arr1,arr2)

array([[16, 26, 36]])