# intro to numpy arrays
- allows us to do mathematical operations, scientific computation & analysis in python language
-Numerical Python
-Arrays= ndarrays
-multidimensional,homogenous,can do element-wise ,easy to access

# dimensions in array

0D array-scalar: an array made up of only one numerical value
1D array-vector:list of elements
2D: list of elements are the elements
3D: 2D arrays are the elements

In [1]:
# arrays from lists or tuples
# np.array()

import numpy as np

my_list = [1,2,3,4,5]

arr1 = np.array(my_list)
arr1

array([1, 2, 3, 4, 5])

In [ ]:
my_list = [[1,2,3],[4,5,6]]
arr2 = np.array(my_list)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# array from random
arr3 = np.random.rand(2,3)
arr3

array([[0.64668171, 0.82050997, 0.88082228],
       [0.05269202, 0.87048306, 0.82441602]])

In [ ]:
arr4 = np.random.randint(5,size=(5,5))
print(arr4)

[[1 0 3 4 2]
 [0 2 1 4 1]
 [2 4 2 0 1]
 [2 0 2 1 3]
 [0 3 2 1 4]]


In [8]:
arr5 = np.full((2,3,4),9)
arr5

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [9]:
arr6 = np.arange(0,50,2)
arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [10]:
arr7 = np.identity(4)
arr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
arr8 = np.eye(4,k=1)
arr8

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [18]:
arr9 = np.random.randint(35,40,size=(5,7))
print(arr9)

[[38 36 39 39 36 36 36]
 [39 38 35 35 38 38 35]
 [37 36 35 35 36 37 37]
 [37 38 35 36 36 35 35]
 [36 39 36 37 38 36 38]]


In [20]:
arr10 = np.random.randint(25,size=(30,30))
arr10

array([[11, 23, 23,  7, 21,  8, 21,  0, 14,  1, 19,  3,  9,  5,  7, 12,
         8,  2, 23,  4, 14, 23,  4,  9,  4,  7, 23, 14,  6, 20],
       [ 1,  8, 16, 12, 22,  1,  7, 19, 17, 19, 10,  8, 13, 23,  6, 13,
         7,  1, 15,  2, 16, 17,  4,  4, 11,  2, 15, 19, 22, 19],
       [19, 19,  0, 20, 19,  6,  3,  2, 21,  9, 11, 13, 16,  0, 13, 16,
         2, 19, 17, 24, 21,  2, 13,  3,  1,  2, 17,  1,  6, 12],
       [19, 16, 11, 22, 17,  5,  1, 24, 13, 23, 22, 17,  0,  9, 22, 24,
         6,  7,  7,  4, 16,  7,  8, 11, 10, 16, 15, 14, 19, 21],
       [13, 19, 24,  2, 18, 20, 14, 24, 23,  3,  4, 23, 18,  0,  4, 21,
         9,  8,  4,  6, 19,  0,  7, 18, 15, 21,  0, 16,  7, 24],
       [ 9, 18, 20,  2,  9, 19,  5,  7, 22,  5,  9,  9,  8,  4, 17,  6,
         0,  5,  2, 13, 13, 24, 15, 15, 15, 18, 22, 21, 18, 16],
       [21,  2, 18, 15, 17, 22,  8,  2, 15, 10, 17, 21,  4, 18,  6,  2,
         2, 16, 16, 15, 23,  7,  6,  3,  4,  4,  1, 18, 22, 16],
       [22, 14,  2,  2, 22,  3, 23,  5,  

In [32]:
# array attributes-characteristics
# -dimensions
# -size
# -shape
# -data type

import numpy as np

x1 = np.random.randint(50,size=(3,5)).reshape(5,3)
print(x1)

[[ 2 30 17]
 [37 31 25]
 [21 40 14]
 [40 35 40]
 [23 23 17]]


In [33]:
x1.reshape(3,5)

array([[ 2, 30, 17, 37, 31],
       [25, 21, 40, 14, 40],
       [35, 40, 23, 23, 17]], dtype=int32)

In [25]:
print(x1.shape)

(3, 5)


In [26]:
print(x1.ndim)

2


In [27]:
print(x1.dtype)

int32


In [29]:
print(x1.size)

15


# indexing
accessing element in array

In [36]:
x2 = np.arange(10,20,2)
print(x2[3])

16


In [40]:
x3 = np.arange(10,100,3).reshape(2,5,3)
x3

array([[[10, 13, 16],
        [19, 22, 25],
        [28, 31, 34],
        [37, 40, 43],
        [46, 49, 52]],

       [[55, 58, 61],
        [64, 67, 70],
        [73, 76, 79],
        [82, 85, 88],
        [91, 94, 97]]])

In [43]:
x3[1,2,1]

np.int64(100)

In [45]:
x3[1,2,1]=100
x3

array([[[ 10,  13,  16],
        [ 19,  22,  25],
        [ 28,  31,  34],
        [ 37,  40,  43],
        [ 46,  49,  52]],

       [[ 55,  58,  61],
        [ 64,  67,  70],
        [ 73, 100,  79],
        [ 82,  85,  88],
        [ 91,  94,  97]]])

# slicing

In [47]:
# (start,stop,step)

x4 = np.arange(10)
x4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
x4[4:7]

array([4, 5, 6])

In [106]:
x5 = np.array([23,56,78,90,67,50,45,89,34,69,33,54]).reshape(3,4)
x5

array([[23, 56, 78, 90],
       [67, 50, 45, 89],
       [34, 69, 33, 54]])

In [66]:
# [row,colomun]

x5[1:3,1]

array([67, 89])

In [67]:
x5[0:3,2]

array([78, 50, 34])

In [72]:
x5[0:2,1:3]

array([[56, 78],
       [67, 50]])

In [84]:
x6 = np.array([23,56,78,90,67,50,45,89,34,10,30,29]).reshape(3,4)
x6

array([[23, 56, 78, 90],
       [67, 50, 45, 89],
       [34, 10, 30, 29]])

In [78]:
x6[:,3]

array([90, 89, 29])

In [86]:
x4

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# rearrange from the back
x4[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [ ]:
# PALINDROME
a = 'BOB'
b = a[::-1]
if a == b :
    print('This is a palindrome')
else:
    print('This is not a palindrome')

This is not a palindrome


# Vectorization
Universal functions-arithmetic,trigonometic,aggregation

In [95]:
x5

array([[23, 56, 78],
       [90, 67, 50],
       [45, 89, 34]])

In [96]:
np.add(x5,5)

array([[28, 61, 83],
       [95, 72, 55],
       [50, 94, 39]])

In [97]:
np.power(x5,2)

array([[ 529, 3136, 6084],
       [8100, 4489, 2500],
       [2025, 7921, 1156]])

In [98]:
np.sqrt(x5)

array([[4.79583152, 7.48331477, 8.83176087],
       [9.48683298, 8.18535277, 7.07106781],
       [6.70820393, 9.43398113, 5.83095189]])

In [101]:
x7 = np.random.rand(20)
x7

array([0.0980353 , 0.82227406, 0.28844951, 0.26919327, 0.96172306,
       0.34126439, 0.36572323, 0.27725751, 0.74028978, 0.41987498,
       0.34410471, 0.11522783, 0.01707069, 0.90531674, 0.36103965,
       0.94890951, 0.58568859, 0.17404319, 0.35317346, 0.2074541 ])

In [104]:
np.tan(x7)

array([0.09835059, 1.07661166, 0.296725  , 0.2758898 , 1.43360888,
       0.35516012, 0.38295112, 0.2845874 , 0.91362106, 0.4464226 ,
       0.35836195, 0.11574053, 0.01707235, 1.27401087, 0.37759026,
       1.39516457, 0.66332934, 0.17582206, 0.36862899, 0.21048233])

In [113]:
x5

array([[23, 56, 78, 90],
       [67, 50, 45, 89],
       [34, 69, 33, 54]])

In [115]:
np.sum(x5, axis=1)

array([247, 251, 190])

In [116]:
np.sum(x5, axis=0)

array([124, 175, 156, 233])

In [118]:
arr1=np.arange(5)
arr2=np.array([1,2,3,4,5])
np.add(arr1,arr2)

array([1, 3, 5, 7, 9])

In [119]:
arr1

array([0, 1, 2, 3, 4])

# BROADCASTING
if trailing dimension is 1 or equal
same or 1
broadcast the array that has the smaller dimension into the bigger

In [ ]:
arr1 = np.array([10,20,30])
arr2 = np.random.randint(7,size=(3,2))
# print(arr1)
# print(arr2)
np.add(arr1,arr2)

array([[16, 26, 36]])

# Masks, comparisons & boolean operators in numpy

mask: special array made of speacial booloean values

In [2]:
import numpy as np
weights = np.array([52,43,61,30,72,51,28,64])
weights

array([52, 43, 61, 30, 72, 51, 28, 64])

In [3]:
obese_mask = weights>60
obese_mask

array([False, False,  True, False,  True, False, False,  True])

In [6]:
obese_patients = weights[obese_mask]
obese_patients

array([61, 72, 64])

In [7]:
moderate_mask = (weights>=40) & (weights<=60)
moderate_mask

array([ True,  True, False, False, False,  True, False, False])

In [10]:
not_obese_mask = ~(weights>60)
not_obese_mask

array([ True,  True, False,  True, False,  True,  True, False])

In [11]:
not_obese_patients = weights[not_obese_mask]
not_obese_patients

array([52, 43, 30, 51, 28])

## Fundamentals of panda

1. Data structures
2. File format and importing data into pandas
3. Basic inspection of a df
4. Indexing/slicing of df

In [15]:
# organizes data in: series and a data frame
# csv,tsv,excel,urls

import pandas as pd

# df=pd.read_excel()
# df.head

In [17]:
# webpage url
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_df=pd.read_csv(url)
iris_df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

## Panda fundamentals

In [18]:
import pandas as pd

In [20]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data"
iris_df = pd.read_csv(url)
iris_df.head()

5.1  3.5  1.4  0.2  Iris-setosa
0  4.9  3.0  1.4  0.2  Iris-setosa
1  4.7  3.2  1.3  0.2  Iris-setosa
2  4.6  3.1  1.5  0.2  Iris-setosa
3  5.0  3.6  1.4  0.2  Iris-setosa
4  5.4  3.9  1.7  0.4  Iris-setosa

# Basic info of dataframe

In [65]:
sales_df = pd.read_csv(r"C:\Users\USER\Downloads\Sales.csv")
sales_df.head(10)

Brands             Models           Colors  Memory Storage Camera  Rating  \
0  SAMSUNG       GALAXY M31S      Mirage Black    8 GB  128 GB    Yes     4.3   
1    Nokia                3.2            Steel    2 GB   16 GB    Yes     3.8   
2   realme                C2     Diamond Black    2 GB     NaN    Yes     4.4   
3  Infinix             Note 5         Ice Blue    4 GB   64 GB    Yes     4.2   
4    Apple         iPhone 11             Black     4GB   64 GB    Yes     4.6   
5   GIONEE               L800            Black    8 MB   16 MB    Yes     4.0   
6    Apple    iPhone 13 Mini              Pink    6 GB  512 GB    Yes     NaN   
7    Apple         iPhone XR             Coral    3 GB   64 GB    Yes     4.6   
8  SAMSUNG         Galaxy E5             Brown  1.5 GB   16 GB    Yes     4.2   
9   Xiaomi  Redmi Note 11T 5G  Aquamarine Blue    8 GB  128 GB    Yes     4.3   

   Selling Price  Original Price                    Mobile  Discount  \
0          19330           20999      SAMSUNG GALAXY M31S       1669   
1          10199           10199                 Nokia 3.2         0   
2           6999            7999                realme C2       1000   
3          12999           12999            Infinix Note 5         0   
4          49900           49900          Apple iPhone 11          0   
5           2199            2199               GIONEE L800         0   
6          99900           99900     Apple iPhone 13 Mini          0   
7          42999           47900          Apple iPhone XR       4901   
8          20400           20400        SAMSUNG Galaxy E5          0   
9          21736           22999  Xiaomi Redmi Note 11T 5G      1263   

   discount percentage  
0             7.947998  
1             0.000000  
2            12.501563  
3             0.000000  
4             0.000000  
5             0.000000  
6             0.000000  
7            10.231733  
8             0.000000  
9             5.491543

In [66]:
sales_df.shape

(3114, 12)

In [67]:
# last row
sales_df.tail()

Brands          Models     Colors Memory                Storage Camera  \
3109    POCO       M4 Pro 5G  Cool Blue   6 GB                 128 GB    Yes   
3110   Nokia             225      Black    NaN  Expandable Upto 32 GB    Yes   
3111   Apple      iPhone SE       White   2 GB                 128 GB    Yes   
3112   Apple  iPhone 13 Pro        Gold   6 GB                 128 GB    Yes   
3113  GIONEE             F9        Blue   3 GB                  32 GB    Yes   

      Rating  Selling Price  Original Price                Mobile  Discount  \
3109     4.4          16999           19999        POCO M4 Pro 5G      3000   
3110     3.6           3499            3499             Nokia 225         0   
3111     4.5          44900           44900      Apple iPhone SE          0   
3112     NaN         119900          119900  Apple iPhone 13 Pro          0   
3113     4.2           7900            7900            GIONEE F9          0   

      discount percentage  
3109             15.00075  
3110              0.00000  
3111              0.00000  
3112              0.00000  
3113              0.00000

In [68]:
sales_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3114 entries, 0 to 3113
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   Brands               3114 non-null   object 
 1   Models               3114 non-null   object 
 2   Colors               3114 non-null   object 
 3   Memory               3071 non-null   object 
 4   Storage              3075 non-null   object 
 5   Camera               3114 non-null   object 
 6   Rating               2970 non-null   float64
 7   Selling Price        3114 non-null   int64  
 8   Original Price       3114 non-null   int64  
 9   Mobile               3114 non-null   object 
 10  Discount             3114 non-null   int64  
 11  discount percentage  3114 non-null   float64
dtypes: float64(2), int64(3), object(7)
memory usage: 292.1+ KB


In [69]:
# summary statistics of numerical columns
sales_df.describe()

Rating  Selling Price  Original Price      Discount  \
count  2970.000000    3114.000000     3114.000000   3114.000000   
mean      4.243098   26436.625562    28333.473025   1896.847463   
std       0.271991   30066.892622    31525.599889   5337.126176   
min       2.300000    1000.000000     1000.000000  -8000.000000   
25%       4.100000    9990.000000    10030.250000      0.000000   
50%       4.300000   15000.000000    16889.500000      0.000000   
75%       4.400000   28999.000000    31500.000000   2000.000000   
max       5.000000  179900.000000   189999.000000  75000.000000   

       discount percentage  
count          3114.000000  
mean              6.086788  
std              11.106776  
min            -160.320641  
25%               0.000000  
50%               0.000000  
75%               9.836388  
max              70.610305

In [70]:
# list of columns
sales_df.columns

Index(['Brands', 'Models', 'Colors', 'Memory', 'Storage', 'Camera', 'Rating',
       'Selling Price', 'Original Price', 'Mobile', 'Discount',
       'discount percentage'],
      dtype='object')

Ascending data using iloc & loc

In [71]:
sales_df.head()

Brands        Models         Colors Memory Storage Camera  Rating  \
0  SAMSUNG  GALAXY M31S    Mirage Black   8 GB  128 GB    Yes     4.3   
1    Nokia           3.2          Steel   2 GB   16 GB    Yes     3.8   
2   realme           C2   Diamond Black   2 GB     NaN    Yes     4.4   
3  Infinix        Note 5       Ice Blue   4 GB   64 GB    Yes     4.2   
4    Apple    iPhone 11           Black    4GB   64 GB    Yes     4.6   

   Selling Price  Original Price                Mobile  Discount  \
0          19330           20999  SAMSUNG GALAXY M31S       1669   
1          10199           10199             Nokia 3.2         0   
2           6999            7999            realme C2       1000   
3          12999           12999        Infinix Note 5         0   
4          49900           49900      Apple iPhone 11          0   

   discount percentage  
0             7.947998  
1             0.000000  
2            12.501563  
3             0.000000  
4             0.000000

In [72]:
sales_df[0:1]

Brands        Models        Colors Memory Storage Camera  Rating  \
0  SAMSUNG  GALAXY M31S   Mirage Black   8 GB  128 GB    Yes     4.3   

   Selling Price  Original Price                Mobile  Discount  \
0          19330           20999  SAMSUNG GALAXY M31S       1669   

   discount percentage  
0             7.947998

In [73]:
# iloc - integer location

sales_df.iloc[0]

Brands                              SAMSUNG
Models                         GALAXY M31S 
Colors                         Mirage Black
Memory                                 8 GB
Storage                              128 GB
Camera                                  Yes
Rating                                  4.3
Selling Price                         19330
Original Price                        20999
Mobile                 SAMSUNG GALAXY M31S 
Discount                               1669
discount percentage                7.947998
Name: 0, dtype: object

In [74]:
sales_df.iloc[1000::10]

Brands           Models         Colors Memory                Storage  \
1000   Lenovo    Vibe K5 Plus          Silver   2 GB                  16 GB   
1010    Apple       iPhone XR            Blue   3 GB                  64 GB   
1020    Apple  iPhone 6s Plus      Space Grey   2 GB                  32 GB   
1030   realme                2  Diamond Black   3 GB                    NaN   
1040     ASUS    Zenfone Zoom           White   4 GB                  64 GB   
...       ...              ...            ...    ...                    ...   
3070  Infinix          Hot 11S     Green Wave   4 GB                 128 GB   
3080   realme            C25Y    Glacier Blue   4 GB                  64 GB   
3090    Apple       iPhone 13            Blue    4GB                 512 GB   
3100     OPPO              A1K            Red   2 GB                  32 GB   
3110    Nokia              225          Black    NaN  Expandable Upto 32 GB   

     Camera  Rating  Selling Price  Original Price                 Mobile  \
1000    Yes     4.0           8499            8499   Lenovo Vibe K5 Plus    
1010    Yes     4.6          42999           47900       Apple iPhone XR    
1020    Yes     4.4          34900           34900  Apple iPhone 6s Plus    
1030    Yes     4.5           9990            9990               realme 2   
1040    Yes     3.6          37999           37999     ASUS Zenfone Zoom    
...     ...     ...            ...             ...                    ...   
3070    Yes     4.3          11999           14999        Infinix Hot 11S   
3080    Yes     4.5          10999           12999           realme C25Y    
3090    Yes     NaN         109900          109900       Apple iPhone 13    
3100    Yes     4.3           8490           13400               OPPO A1K   
3110    Yes     3.6           3499            3499              Nokia 225   

      Discount  discount percentage  
1000         0             0.000000  
1010      4901            10.231733  
1020         0             0.000000  
1030         0             0.000000  
1040         0             0.000000  
...        ...                  ...  
3070      3000            20.001333  
3080      2000            15.385799  
3090         0             0.000000  
3100      4910            36.641791  
3110         0             0.000000  

[212 rows x 12 columns]

In [75]:
sales_df.iloc[0:5,0:2]

Brands        Models
0  SAMSUNG  GALAXY M31S 
1    Nokia           3.2
2   realme           C2 
3  Infinix        Note 5
4    Apple    iPhone 11

In [76]:
sales_df.iloc[0:5,[0,2]]

Brands         Colors
0  SAMSUNG   Mirage Black
1    Nokia          Steel
2   realme  Diamond Black
3  Infinix       Ice Blue
4    Apple          Black

Q1: 1st 10 rows,(Brand,SP,OP)

In [77]:
# accessing 1 row 
sales_df.iloc[0]

Brands                              SAMSUNG
Models                         GALAXY M31S 
Colors                         Mirage Black
Memory                                 8 GB
Storage                              128 GB
Camera                                  Yes
Rating                                  4.3
Selling Price                         19330
Original Price                        20999
Mobile                 SAMSUNG GALAXY M31S 
Discount                               1669
discount percentage                7.947998
Name: 0, dtype: object

In [78]:
sales_df.iloc[[0,20,100,1034,3000]]

Brands              Models          Colors Memory Storage Camera  \
0      SAMSUNG        GALAXY M31S     Mirage Black   8 GB  128 GB    Yes   
20    Motorola                   M            Grey   4 GB   64 GB    Yes   
100      Apple  iPhone 11 Pro Max             Gold    4GB  256 GB    Yes   
1034   SAMSUNG         Galaxy M12            Black   6 GB  128 GB    Yes   
3000  Motorola                  G5  Frosted Silver   6 GB  128 GB    Yes   

      Rating  Selling Price  Original Price                    Mobile  \
0        4.3          19330           20999      SAMSUNG GALAXY M31S    
20       3.9           9999            9999                Motorola M   
100      4.7         131900          131900  Apple iPhone 11 Pro Max    
1034     4.2          13984           15499       SAMSUNG Galaxy M12    
3000     4.2          20999           24999               Motorola G5   

      Discount  discount percentage  
0         1669             7.947998  
20           0             0.000000  
100          0             0.000000  
1034      1515             9.774824  
3000      4000            16.000640

In [79]:
# one column
sales_df.iloc[:,0]

0       SAMSUNG
1         Nokia
2        realme
3       Infinix
4         Apple
         ...   
3109       POCO
3110      Nokia
3111      Apple
3112      Apple
3113     GIONEE
Name: Brands, Length: 3114, dtype: object

In [80]:
# multiple columns
sales_df.iloc[:,[0,3,7]]

Brands Memory  Selling Price
0     SAMSUNG   8 GB          19330
1       Nokia   2 GB          10199
2      realme   2 GB           6999
3     Infinix   4 GB          12999
4       Apple    4GB          49900
...       ...    ...            ...
3109     POCO   6 GB          16999
3110    Nokia    NaN           3499
3111    Apple   2 GB          44900
3112    Apple   6 GB         119900
3113   GIONEE   3 GB           7900

[3114 rows x 3 columns]

In [81]:
sales_df.iloc[0:10,[0,7,8]]

Brands  Selling Price  Original Price
0  SAMSUNG          19330           20999
1    Nokia          10199           10199
2   realme           6999            7999
3  Infinix          12999           12999
4    Apple          49900           49900
5   GIONEE           2199            2199
6    Apple          99900           99900
7    Apple          42999           47900
8  SAMSUNG          20400           20400
9   Xiaomi          21736           22999

Q2: model & specs

In [82]:
sales_df.iloc[:,1:6]

Models         Colors Memory                Storage Camera
0       GALAXY M31S    Mirage Black   8 GB                 128 GB    Yes
1                3.2          Steel   2 GB                  16 GB    Yes
2                C2   Diamond Black   2 GB                    NaN    Yes
3             Note 5       Ice Blue   4 GB                  64 GB    Yes
4         iPhone 11           Black    4GB                  64 GB    Yes
...              ...            ...    ...                    ...    ...
3109       M4 Pro 5G      Cool Blue   6 GB                 128 GB    Yes
3110             225          Black    NaN  Expandable Upto 32 GB    Yes
3111      iPhone SE           White   2 GB                 128 GB    Yes
3112  iPhone 13 Pro            Gold   6 GB                 128 GB    Yes
3113             F9            Blue   3 GB                  32 GB    Yes

[3114 rows x 5 columns]

## LOC

In [84]:
# one row
sales_df.loc[0, "Brands"]

'SAMSUNG'

In [87]:
# accessing 1 row with loc
data={
    'Name': ['Ivy', 'Victor', 'Kelvin'],
    'Age': [25, 27, 31],
    'Subject': ['English','Math','Chemistry']
}

df = pd.DataFrame(data,index=['A','B','C'])

In [88]:
df.head()

Name  Age    Subject
A     Ivy   25    English
B  Victor   27       Math
C  Kelvin   31  Chemistry

In [89]:
# access 1 row 
df.loc['C']

Name          Kelvin
Age               31
Subject    Chemistry
Name: C, dtype: object

In [93]:
df.loc[['A','C']]

Name  Age    Subject
A     Ivy   25    English
C  Kelvin   31  Chemistry

In [94]:
# access 1 & more
df.loc[:,'Age']

A    25
B    27
C    31
Name: Age, dtype: int64

In [98]:
# grades for Ivy
df.loc['A','Age']

np.int64(25)

In [100]:
# age & name
df.loc[:,['Age','Name']]

Age    Name
A   25     Ivy
B   27  Victor
C   31  Kelvin

In [102]:
df.loc[['A','C'],['Age','Subject']]

Age    Subject
A   25    English
C   31  Chemistry

Here are some practice questions on using loc and iloc:

Use iloc to get the last 10 records

Use .iloc to extract rows 50 to 100 (inclusive) but only for the columns: Models, Discount, discount percentage

Extract the selling price of the 5th record in the dataframe

Using .iloc, select every 10th row from the dataset and only the even-numbered columns.

In [103]:
import pandas as pd
import numpy as np

In [105]:
sales_df = pd.read_csv(r"C:\Users\USER\desktop\PY_DATA\Sales.csv")
sales_df.head(10)

Brands             Models           Colors  Memory Storage Camera  Rating  \
0  SAMSUNG       GALAXY M31S      Mirage Black    8 GB  128 GB    Yes     4.3   
1    Nokia                3.2            Steel    2 GB   16 GB    Yes     3.8   
2   realme                C2     Diamond Black    2 GB     NaN    Yes     4.4   
3  Infinix             Note 5         Ice Blue    4 GB   64 GB    Yes     4.2   
4    Apple         iPhone 11             Black     4GB   64 GB    Yes     4.6   
5   GIONEE               L800            Black    8 MB   16 MB    Yes     4.0   
6    Apple    iPhone 13 Mini              Pink    6 GB  512 GB    Yes     NaN   
7    Apple         iPhone XR             Coral    3 GB   64 GB    Yes     4.6   
8  SAMSUNG         Galaxy E5             Brown  1.5 GB   16 GB    Yes     4.2   
9   Xiaomi  Redmi Note 11T 5G  Aquamarine Blue    8 GB  128 GB    Yes     4.3   

   Selling Price  Original Price                    Mobile  Discount  \
0          19330           20999      SAMSUNG GALAXY M31S       1669   
1          10199           10199                 Nokia 3.2         0   
2           6999            7999                realme C2       1000   
3          12999           12999            Infinix Note 5         0   
4          49900           49900          Apple iPhone 11          0   
5           2199            2199               GIONEE L800         0   
6          99900           99900     Apple iPhone 13 Mini          0   
7          42999           47900          Apple iPhone XR       4901   
8          20400           20400        SAMSUNG Galaxy E5          0   
9          21736           22999  Xiaomi Redmi Note 11T 5G      1263   

   discount percentage  
0             7.947998  
1             0.000000  
2            12.501563  
3             0.000000  
4             0.000000  
5             0.000000  
6             0.000000  
7            10.231733  
8             0.000000  
9             5.491543

In [106]:
# Use iloc to get the last 10 records
sales_df.iloc[-10:]

Brands              Models     Colors  Memory                Storage  \
3104       LG           Q Stylus       Black    3 GB                  32 GB   
3105    Apple  iPhone 13 Pro Max        Gold    6 GB                 128 GB   
3106     ASUS    ROG Phone 5 Pro       Black   16 GB                 512 GB   
3107  SAMSUNG    Galaxy S Duos 2       Black  512 MB                   4 GB   
3108  SAMSUNG           Metro 313      Black    4 MB                   2 MB   
3109     POCO           M4 Pro 5G  Cool Blue    6 GB                 128 GB   
3110    Nokia                 225      Black     NaN  Expandable Upto 32 GB   
3111    Apple          iPhone SE       White    2 GB                 128 GB   
3112    Apple      iPhone 13 Pro        Gold    6 GB                 128 GB   
3113   GIONEE                 F9        Blue    3 GB                  32 GB   

     Camera  Rating  Selling Price  Original Price                    Mobile  \
3104    Yes     3.8          20000           20000              LG Q Stylus    
3105    Yes     NaN         129900          129900  Apple iPhone 13 Pro Max    
3106    Yes     NaN          69999           75999     ASUS ROG Phone 5 Pro    
3107    Yes     4.0           5999            5999  SAMSUNG Galaxy S Duos 2    
3108    Yes     4.2           2299            2299         SAMSUNG Metro 313   
3109    Yes     4.4          16999           19999            POCO M4 Pro 5G   
3110    Yes     3.6           3499            3499                 Nokia 225   
3111    Yes     4.5          44900           44900          Apple iPhone SE    
3112    Yes     NaN         119900          119900      Apple iPhone 13 Pro    
3113    Yes     4.2           7900            7900                GIONEE F9    

      Discount  discount percentage  
3104         0             0.000000  
3105         0             0.000000  
3106      6000             7.894841  
3107         0             0.000000  
3108         0             0.000000  
3109      3000            15.000750  
3110         0             0.000000  
3111         0             0.000000  
3112         0             0.000000  
3113         0             0.000000

In [107]:
# Use .iloc to extract rows 50 to 100 (inclusive) but only for the columns: Models, Discount, discount percentage
sales_df.iloc[50:101, [1, 10, 11]]

Models  Discount  discount percentage
50                          9i      2000            12.500781
51              iPhone 7 Plus          0             0.000000
52                   iPhone 8        901             2.258145
53                      Z Play         0             0.000000
54                  iPhone 11          0             0.000000
55                    K4 Note          0             0.000000
56   Reno4 Pro Special Edition      3000             7.896815
57                    Reno7 5G      8991            23.666754
58              Galaxy Note 9      19991            27.018516
59                         7i          0             0.000000
60                       A390          0             0.000000
61            Galaxy S6 Edge+      33988            54.829967
62                   Stylus 3          0             0.000000
63                  Narzo 20A       2500            22.729339
64                   Marathon          0             0.000000
65              Mi 11X Pro 5G       1200             3.200854
66                         G5          0             0.000000
67                      6 Pro          0             0.000000
68               REDMI Note 9       3000            20.001333
69                         A5s      5000            31.269543
70                          F1         0             0.000000
71                     One E9+         0             0.000000
72                Galaxy M30S       2600            15.672092
73                  MI 11X 5G       3503            12.512949
74                         A3s         0             0.000000
75                 Wildfire X          0             0.000000
76                 Galaxy S10          0             0.000000
77                     Note 11      2000            11.765398
78                 Galaxy M31          0             0.000000
79     Galaxy A7 2016 Edition          0             0.000000
80             Galaxy J2 Core          0             0.000000
81                         A83         0             0.000000
82          11i Hypercharge 5G      5000            15.625488
83                  Zenfone C          0             0.000000
84                 Galaxy F12       1500            10.715051
85               Galaxy F23 5G      7000            30.436106
86               Redmi Note 5          0             0.000000
87                         A5s         0             0.000000
88             Galaxy S6 Edge          0             0.000000
89                         F15      5000            23.820867
90                      5 Pro          0             0.000000
91                  iPhone 12       1901             2.681241
92          iPhone 12 Pro Max          0             0.000000
93                     Reno2 F         0             0.000000
94                 X50 Pro 5G          0             0.000000
95                     F19 Pro      2500             9.619084
96                          F7         0             0.000000
97                     F8 Neo          0             0.000000
98              Stylus 2 Plus          0             0.000000
99                     Mi 11X          0             0.000000
100         iPhone 11 Pro Max          0             0.000000

In [108]:
# Extract the selling price of the 5th record in the dataframe
sales_df.iloc[4, 7]

np.int64(49900)

In [109]:
# Using .iloc, select every 10th row from the dataset and only the even-numbered columns.
sales_df.iloc[::10, ::2]

Brands        Colors                Storage  Rating  Original Price  \
0      SAMSUNG  Mirage Black                 128 GB     4.3           20999   
10     SAMSUNG         Black                  64 GB     4.2           11989   
20    Motorola          Grey                  64 GB     3.9            9999   
30     SAMSUNG         Black                  64 GB     4.5           14990   
40      realme    That Green                 128 GB     4.5           12999   
...        ...           ...                    ...     ...             ...   
3070   Infinix    Green Wave                 128 GB     4.3           14999   
3080    realme  Glacier Blue                  64 GB     4.5           12999   
3090     Apple          Blue                 512 GB     NaN          109900   
3100      OPPO           Red                  32 GB     4.3           13400   
3110     Nokia         Black  Expandable Upto 32 GB     3.6            3499   

      Discount  
0         1669  
10           0  
20           0  
30           0  
40        1000  
...        ...  
3070      3000  
3080      2000  
3090         0  
3100      4910  
3110         0  

[312 rows x 6 columns]

# Filtering dataframes based on conditions

In [110]:
sales_df.head()

Brands        Models         Colors Memory Storage Camera  Rating  \
0  SAMSUNG  GALAXY M31S    Mirage Black   8 GB  128 GB    Yes     4.3   
1    Nokia           3.2          Steel   2 GB   16 GB    Yes     3.8   
2   realme           C2   Diamond Black   2 GB     NaN    Yes     4.4   
3  Infinix        Note 5       Ice Blue   4 GB   64 GB    Yes     4.2   
4    Apple    iPhone 11           Black    4GB   64 GB    Yes     4.6   

   Selling Price  Original Price                Mobile  Discount  \
0          19330           20999  SAMSUNG GALAXY M31S       1669   
1          10199           10199             Nokia 3.2         0   
2           6999            7999            realme C2       1000   
3          12999           12999        Infinix Note 5         0   
4          49900           49900      Apple iPhone 11          0   

   discount percentage  
0             7.947998  
1             0.000000  
2            12.501563  
3             0.000000  
4             0.000000

In [111]:
# filter the dataframe for all phones above 15,000
sales_df[sales_df['Selling Price'] > 15000].head()

Brands           Models        Colors  Memory Storage Camera  Rating  \
0  SAMSUNG     GALAXY M31S   Mirage Black    8 GB  128 GB    Yes     4.3   
4    Apple       iPhone 11          Black     4GB   64 GB    Yes     4.6   
6    Apple  iPhone 13 Mini           Pink    6 GB  512 GB    Yes     NaN   
7    Apple       iPhone XR          Coral    3 GB   64 GB    Yes     4.6   
8  SAMSUNG       Galaxy E5          Brown  1.5 GB   16 GB    Yes     4.2   

   Selling Price  Original Price                 Mobile  Discount  \
0          19330           20999   SAMSUNG GALAXY M31S       1669   
4          49900           49900       Apple iPhone 11          0   
6          99900           99900  Apple iPhone 13 Mini          0   
7          42999           47900       Apple iPhone XR       4901   
8          20400           20400     SAMSUNG Galaxy E5          0   

   discount percentage  
0             7.947998  
4             0.000000  
6             0.000000  
7            10.231733  
8             0.000000

In [112]:
sales_df.loc[sales_df['Selling Price']>15000].head()

Brands           Models        Colors  Memory Storage Camera  Rating  \
0  SAMSUNG     GALAXY M31S   Mirage Black    8 GB  128 GB    Yes     4.3   
4    Apple       iPhone 11          Black     4GB   64 GB    Yes     4.6   
6    Apple  iPhone 13 Mini           Pink    6 GB  512 GB    Yes     NaN   
7    Apple       iPhone XR          Coral    3 GB   64 GB    Yes     4.6   
8  SAMSUNG       Galaxy E5          Brown  1.5 GB   16 GB    Yes     4.2   

   Selling Price  Original Price                 Mobile  Discount  \
0          19330           20999   SAMSUNG GALAXY M31S       1669   
4          49900           49900       Apple iPhone 11          0   
6          99900           99900  Apple iPhone 13 Mini          0   
7          42999           47900       Apple iPhone XR       4901   
8          20400           20400     SAMSUNG Galaxy E5          0   

   discount percentage  
0             7.947998  
4             0.000000  
6             0.000000  
7            10.231733  
8             0.000000

In [113]:
# use loc to view mobile phones where the memory is more than 8GB
sales_df.loc[sales_df['Memory'] == '8 GB']

Brands                      Models            Colors Memory Storage  \
0     SAMSUNG                GALAXY M31S       Mirage Black   8 GB  128 GB   
9      Xiaomi           Redmi Note 11T 5G   Aquamarine Blue   8 GB  128 GB   
14       vivo                      V23 5G     Sunshine Gold   8 GB  128 GB   
32    SAMSUNG              Galaxy Note 9     Midnight Black   8 GB  512 GB   
38     realme               X3 SuperZoom       Arctic White   8 GB     NaN   
...       ...                         ...               ...    ...     ...   
3058  SAMSUNG                 Galaxy A80      Phantom Black   8 GB  128 GB   
3059     OPPO                       Reno2        Ocean Blue   8 GB  256 GB   
3066  Infinix  Note 11S Free Fire Edition        Haze Green   8 GB  128 GB   
3069  SAMSUNG                 Galaxy A51   Prism Crush Blue   8 GB  128 GB   
3073   realme            Narzo 30 Pro 5G       Blade Silver   8 GB  128 GB   

     Camera  Rating  Selling Price  Original Price  \
0       Yes     4.3          19330           20999   
9       Yes     4.3          21736           22999   
14      Yes     4.4          29990           34990   
32      Yes     4.6          49999           49999   
38      Yes     4.3          29999           31999   
...     ...     ...            ...             ...   
3058    Yes     4.4          29899           29899   
3059    Yes     4.4          38990           39990   
3066    Yes     4.3          15999           18999   
3069    Yes     4.3          22499           29999   
3073    Yes     4.3          19999           21999   

                                  Mobile  Discount  discount percentage  
0                   SAMSUNG GALAXY M31S       1669             7.947998  
9               Xiaomi Redmi Note 11T 5G      1263             5.491543  
14                           vivo V23 5G      5000            14.289797  
32                SAMSUNG Galaxy Note 9          0             0.000000  
38                  realme X3 SuperZoom       2000             6.250195  
...                                  ...       ...                  ...  
3058                 SAMSUNG Galaxy A80          0             0.000000  
3059                          OPPO Reno2      1000             2.500625  
3066  Infinix Note 11S Free Fire Edition      3000            15.790305  
3069                 SAMSUNG Galaxy A51       7500            25.000833  
3073             realme Narzo 30 Pro 5G       2000             9.091322  

[345 rows x 12 columns]

In [114]:
# access Xiaomi phones that have a RAM of 128 GB
# when applying two conditions, make sure it's on it's own brackets
sales_df.loc[(sales_df['Brands'] == 'Xiaomi') | (sales_df['Storage'] == '128 GB')].head()

Brands             Models           Colors Memory Storage Camera  Rating  \
0   SAMSUNG       GALAXY M31S      Mirage Black   8 GB  128 GB    Yes     4.3   
9    Xiaomi  Redmi Note 11T 5G  Aquamarine Blue   8 GB  128 GB    Yes     4.3   
12   realme             X7 5G            Nebula   6 GB  128 GB    Yes     4.3   
14     vivo             V23 5G    Sunshine Gold   8 GB  128 GB    Yes     4.4   
23   realme                X3      Arctic White   6 GB  128 GB    Yes     4.4   

    Selling Price  Original Price                    Mobile  Discount  \
0           19330           20999      SAMSUNG GALAXY M31S       1669   
9           21736           22999  Xiaomi Redmi Note 11T 5G      1263   
12          19999           21999             realme X7 5G       2000   
14          29990           34990               vivo V23 5G      5000   
23          24999           26999                realme X3       2000   

    discount percentage  
0              7.947998  
9              5.491543  
12             9.091322  
14            14.289797  
23             7.407682

In [115]:
sales_df[(sales_df['Brands'] == 'Xiaomi') | (sales_df['Storage'] == '128 GB')].head()

Brands             Models           Colors Memory Storage Camera  Rating  \
0   SAMSUNG       GALAXY M31S      Mirage Black   8 GB  128 GB    Yes     4.3   
9    Xiaomi  Redmi Note 11T 5G  Aquamarine Blue   8 GB  128 GB    Yes     4.3   
12   realme             X7 5G            Nebula   6 GB  128 GB    Yes     4.3   
14     vivo             V23 5G    Sunshine Gold   8 GB  128 GB    Yes     4.4   
23   realme                X3      Arctic White   6 GB  128 GB    Yes     4.4   

    Selling Price  Original Price                    Mobile  Discount  \
0           19330           20999      SAMSUNG GALAXY M31S       1669   
9           21736           22999  Xiaomi Redmi Note 11T 5G      1263   
12          19999           21999             realme X7 5G       2000   
14          29990           34990               vivo V23 5G      5000   
23          24999           26999                realme X3       2000   

    discount percentage  
0              7.947998  
9              5.491543  
12             9.091322  
14            14.289797  
23             7.407682

In [116]:
# produce dataframe : all  phones with more than 4 GB and costs more than 10,000
sales_df[(sales_df['Memory'] > '4 GB') & (sales_df['Selling Price'] > 10000)]

Brands              Models           Colors Memory Storage Camera  \
0     SAMSUNG        GALAXY M31S      Mirage Black   8 GB  128 GB    Yes   
4       Apple          iPhone 11             Black    4GB   64 GB    Yes   
6       Apple     iPhone 13 Mini              Pink   6 GB  512 GB    Yes   
9      Xiaomi   Redmi Note 11T 5G  Aquamarine Blue   8 GB  128 GB    Yes   
11      Apple          iPhone 11               Red    4GB  256 GB    Yes   
...       ...                 ...              ...    ...     ...    ...   
3090    Apple          iPhone 13              Blue    4GB  512 GB    Yes   
3095   Xiaomi          11 Lite NE   Diamond Dazzle   6 GB  128 GB    Yes   
3105    Apple  iPhone 13 Pro Max              Gold   6 GB  128 GB    Yes   
3109     POCO           M4 Pro 5G        Cool Blue   6 GB  128 GB    Yes   
3112    Apple      iPhone 13 Pro              Gold   6 GB  128 GB    Yes   

      Rating  Selling Price  Original Price                    Mobile  \
0        4.3          19330           20999      SAMSUNG GALAXY M31S    
4        4.6          49900           49900          Apple iPhone 11    
6        NaN          99900           99900     Apple iPhone 13 Mini    
9        4.3          21736           22999  Xiaomi Redmi Note 11T 5G   
11       4.6          64900           64900          Apple iPhone 11    
...      ...            ...             ...                       ...   
3090     NaN         109900          109900          Apple iPhone 13    
3095     4.4          24798           24798         Xiaomi 11 Lite NE   
3105     NaN         129900          129900  Apple iPhone 13 Pro Max    
3109     4.4          16999           19999            POCO M4 Pro 5G   
3112     NaN         119900          119900      Apple iPhone 13 Pro    

      Discount  discount percentage  
0         1669             7.947998  
4            0             0.000000  
6            0             0.000000  
9         1263             5.491543  
11           0             0.000000  
...        ...                  ...  
3090         0             0.000000  
3095         0             0.000000  
3105         0             0.000000  
3109      3000            15.000750  
3112         0             0.000000  

[981 rows x 12 columns]

In [117]:
# filter dataframe for all apple  and samsung phones which have no discount
sales_df.loc[sales_df['Brands'].isin(['Samsung','Apple','Lenovo']).tail(30) & (sales_df['Discount'] == 0)]

Brands              Models      Colors Memory Storage Camera  Rating  \
3090  Apple          iPhone 13         Blue    4GB  512 GB    Yes     NaN   
3093  Apple          iPhone XS         Gold   4 GB  512 GB    Yes     4.7   
3103  Apple           iPhone X   Space Gray   3 GB   64 GB    Yes     4.6   
3105  Apple  iPhone 13 Pro Max         Gold   6 GB  128 GB    Yes     NaN   
3111  Apple          iPhone SE        White   2 GB  128 GB    Yes     4.5   
3112  Apple      iPhone 13 Pro         Gold   6 GB  128 GB    Yes     NaN   

      Selling Price  Original Price                    Mobile  Discount  \
3090         109900          109900          Apple iPhone 13          0   
3093         134900          134900          Apple iPhone XS          0   
3103          91900           91900           Apple iPhone X          0   
3105         129900          129900  Apple iPhone 13 Pro Max          0   
3111          44900           44900          Apple iPhone SE          0   
3112         119900          119900      Apple iPhone 13 Pro          0   

      discount percentage  
3090                  0.0  
3093                  0.0  
3103                  0.0  
3105                  0.0  
3111                  0.0  
3112                  0.0

Grouping and aggregation

In [118]:
# groupby function
# split-apply-combine
# df.groupby('split')['apply'].agg()
sales_df.groupby('Brands')['Selling Price'].agg('mean')

Brands
ASUS            20326.915254
Apple           81985.560724
GIONEE           7135.093023
Google Pixel    61391.862069
HTC             28314.381818
IQOO            37190.000000
Infinix         11092.178808
LG              19323.181818
Lenovo          10083.842975
Motorola        16357.466667
Nokia            9428.657277
OPPO            18560.488462
POCO            16870.621622
SAMSUNG         24296.248957
Xiaomi          16941.909091
realme          16396.535168
vivo            23866.241935
Name: Selling Price, dtype: float64

In [119]:
# HIGHEST AVERAGE PRICE
sales_df.groupby('Brands')['Selling Price'].agg('mean').sort_values(ascending=False)

Brands
Apple           81985.560724
Google Pixel    61391.862069
IQOO            37190.000000
HTC             28314.381818
SAMSUNG         24296.248957
vivo            23866.241935
ASUS            20326.915254
LG              19323.181818
OPPO            18560.488462
Xiaomi          16941.909091
POCO            16870.621622
realme          16396.535168
Motorola        16357.466667
Infinix         11092.178808
Lenovo          10083.842975
Nokia            9428.657277
GIONEE           7135.093023
Name: Selling Price, dtype: float64

In [120]:
#  which brand has been given the highest discount
sales_df.groupby('Brands')['Discount'].agg('mean').idxmax

<bound method Series.idxmax of Brands
ASUS            1258.474576
Apple           2931.811370
GIONEE           683.519380
Google Pixel     620.344828
HTC                0.000000
IQOO            3800.000000
Infinix          925.907285
LG              3044.595960
Lenovo           266.669421
Motorola        4323.895238
Nokia            745.732394
OPPO            2050.776923
POCO            2614.864865
SAMSUNG         2535.781641
Xiaomi           911.343434
realme          1441.599388
vivo            1696.661290
Name: Discount, dtype: float64>

In [124]:
# which brand did we sell the most of
sales_df.groupby('Brands')['Selling Price'].agg('count').sort_values(ascending=False)

Brands
SAMSUNG         719
Apple           387
realme          327
OPPO            260
Nokia           213
Xiaomi          198
Infinix         151
GIONEE          129
vivo            124
Lenovo          121
ASUS            118
Motorola        105
LG               99
POCO             74
HTC              55
Google Pixel     29
IQOO              5
Name: Selling Price, dtype: int64

In [125]:
# which brand has the highest number of models
sales_df.groupby('Brands')['Models'].nunique().sort_values(ascending=False)

Brands
SAMSUNG         211
Nokia            83
OPPO             77
LG               64
realme           62
GIONEE           61
vivo             59
Lenovo           55
Motorola         50
Xiaomi           49
Infinix          41
ASUS             33
HTC              29
Apple            28
POCO             14
Google Pixel     11
IQOO              1
Name: Models, dtype: int64

In [126]:
# highest price range
sales_df.groupby('Brands')['Selling Price'].agg(lambda x: x.max()- x.min())

Brands
ASUS             75500
Apple           154901
GIONEE           20400
Google Pixel     80000
HTC              55991
IQOO              5000
Infinix          13050
LG               55000
Lenovo           26450
Motorola         84549
Nokia            55299
OPPO             55991
POCO             23000
SAMSUNG         168900
Xiaomi           48500
realme           41500
vivo             72000
Name: Selling Price, dtype: int64

## Combine datasets
1. .join()
2. 

In [1]:
import pandas as pd
import numpy as np

In [8]:
df1 = pd.read_csv(r"datasets/data_1.csv")
df2 = pd.read_csv(r"C:\Users\USER\desktop\PY_DATA\datasets\data_2.csv")
print(df1)
print(df2)

   FellowshipID FirstName     Skills
0          1001     Frodo     Hiding
1          1002   Samwise  Gardening
2          1003   Gandalf     Spells
3          1004    Pippin  Fireworks
   FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51


In [7]:
print(df1.shape)
print(df2.shape)

(4, 3)
(5, 3)


In [11]:
# .join() works best with indices, combines based on index
df1.join(df2,lsuffix='1',rsuffix="2")

FellowshipID1 FirstName1     Skills  FellowshipID2 FirstName2   Age
0           1001      Frodo     Hiding           1001      Frodo    50
1           1002    Samwise  Gardening           1002    Samwise    39
2           1003    Gandalf     Spells           1006    Legolas  2931
3           1004     Pippin  Fireworks           1007     Elrond  6520

In [15]:
df1.join(df2,lsuffix='1',rsuffix="2")

FirstName1     Skills  FellowshipID FirstName2  Age
FellowshipID                                                    
1001              Frodo     Hiding           NaN        NaN  NaN
1002            Samwise  Gardening           NaN        NaN  NaN
1003            Gandalf     Spells           NaN        NaN  NaN
1004             Pippin  Fireworks           NaN        NaN  NaN

In [ ]:
# default of join is left join
df1.join(df2,lsuffix='1',rsuffix='2', how='right')

FirstName1 Skills  FellowshipID FirstName2   Age
0        NaN    NaN          1001      Frodo    50
1        NaN    NaN          1002    Samwise    39
2        NaN    NaN          1006    Legolas  2931
3        NaN    NaN          1007     Elrond  6520
4        NaN    NaN          1008   Barromir    51

## pd.merge()
Time series data
Allows for boyh index-bases and column-based combining

In [21]:
df1.reset_index(inplace=True)
df1.reset_index(inplace=True)

In [23]:
df1.drop(['index','level_0'],axis=1,inplace=True)

In [26]:
df2

FellowshipID FirstName   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

In [28]:
pd.merge(df1,df2,how='inner',on='FirstName')

FellowshipID_x FirstName     Skills  FellowshipID_y  Age
0            1001     Frodo     Hiding            1001   50
1            1002   Samwise  Gardening            1002   39

In [29]:
df2.rename(columns={'FirstName':'Name'},inplace=True)
df2

FellowshipID      Name   Age
0          1001     Frodo    50
1          1002   Samwise    39
2          1006   Legolas  2931
3          1007    Elrond  6520
4          1008  Barromir    51

In [ ]:
pd.merge(df1,df2,how='inner',left_on='FirstName',right_on='Age')

### pd.concat

In [30]:
pd.concat([df1,df2],axis=1)

FellowshipID FirstName     Skills  FellowshipID      Name   Age
0        1001.0     Frodo     Hiding          1001     Frodo    50
1        1002.0   Samwise  Gardening          1002   Samwise    39
2        1003.0   Gandalf     Spells          1006   Legolas  2931
3        1004.0    Pippin  Fireworks          1007    Elrond  6520
4           NaN       NaN        NaN          1008  Barromir    51