In [2]:
# intro to numpy arrays
# - allows us to do mathematical operations, scientific computation & analysis in python language
# -Numerical Python
# -Arrays= ndarrays
# -multidimensional,homogenous,can do element-wise ,easy to access

In [1]:
# dimensions in array

# 0D array-scalar: an array made up of only one numerical value
# 1D array-vector:list of elements
# 2D: list of elements are the elements
# 3D: 2D arrays are the elements

In [3]:
# arrays from lists or tuples
# np.array()

import numpy as np

my_list = [1,2,3,4,5]

arr1 = np.array(my_list)
arr1

array([1, 2, 3, 4, 5])

In [5]:
my_list = [[1,2,3],[4,5,6]]
arr2 = np.array(my_list)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

In [6]:
# array from random
arr3 = np.random.rand(2,3)
arr3

array([[0.64668171, 0.82050997, 0.88082228],
       [0.05269202, 0.87048306, 0.82441602]])

In [ ]:
arr4 = np.random.randint(5,size=(5,5))
print(arr4)

[[1 0 3 4 2]
 [0 2 1 4 1]
 [2 4 2 0 1]
 [2 0 2 1 3]
 [0 3 2 1 4]]


In [8]:
arr5 = np.full((2,3,4),9)
arr5

array([[[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]],

       [[9, 9, 9, 9],
        [9, 9, 9, 9],
        [9, 9, 9, 9]]])

In [9]:
arr6 = np.arange(0,50,2)
arr6

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])

In [10]:
arr7 = np.identity(4)
arr7

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [12]:
arr8 = np.eye(4,k=1)
arr8

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])

In [15]:
arr9 = np.random.randint(37,size=(5,7))
print(arr9)

[[21 21  2 34 19 20 36]
 [13 32 11 10 20  0 18]
 [17 28  9 10 35 27  7]
 [ 8  9 14  3 22 16 19]
 [ 9  6  4  0 36  0  2]]


In [17]:
arr10 = np.random.randint(30,size=(25,30))
arr10

array([[27,  0,  6, 20, 19,  8, 17, 17, 25, 10, 12, 16,  9, 29, 24, 24,
        29,  7, 29, 18, 28, 20, 23,  3, 19,  6, 22, 25, 21, 24],
       [24, 28,  3, 13, 28, 26,  0, 11, 22, 26, 16, 28,  1, 27,  4, 21,
         3, 10,  8,  6,  6, 16,  8, 13,  1, 14, 29, 13, 28, 18],
       [18, 15, 29,  2,  4,  1, 25,  6,  8, 21, 22,  1,  5, 14, 25, 17,
        19,  5,  4, 14, 14, 21,  5, 21,  8, 11, 29,  6, 28, 27],
       [13,  8, 15, 18, 27, 21, 25, 21,  8, 27,  7, 12, 13,  0,  9, 22,
         0,  7, 17, 23,  6,  2, 29, 29,  4, 28,  4, 20, 21, 29],
       [27, 10,  5, 12, 25, 27,  6,  1, 28, 26, 16, 14,  0,  8, 17,  0,
        21,  7, 25, 19,  0, 11, 19, 14,  0, 23, 16, 24,  6, 19],
       [25, 22,  2, 20, 28, 19, 12, 21, 22, 25, 10, 21, 27, 15, 26,  7,
        28, 15, 28,  5, 23, 26,  8, 29, 21,  3,  9, 15, 18,  6],
       [ 0, 25, 24, 20, 20, 27,  0, 21, 18,  6, 27, 25, 24, 25,  5, 10,
        23, 25,  9, 18,  4, 23,  5, 24, 17, 25,  9, 18,  4,  9],
       [ 7, 27,  0, 29, 25,  6,  1, 25,  